Graphics lab 4
PrimatElite/gpu-labs pull request #6
Opened 2021-03-27 14:15 UTC by MikhailNakhatovich

1. IBL diffuse
2. Conversion 2D texture to cube texture

2021-03-27 19:20 UTC, anthark requested changes
Все хорошо, кроме того, что источник для IBL оказывается не HDR

2021-03-27 19:20 UTC, anthark commented on graphics/ibl/ibl/Renderer.cpp
> +    D3D11_TEXTURE2D_DESC td = CD3D11_TEXTURE2D_DESC(DXGI_FORMAT_R8G8B8A8_UNORM, cubeSize, cubeSize, 6, 1, D3D11_BIND_SHADER_RESOURCE,
Вы используете нормализованный 8-ми битный формат для environment map и для irradiance, а должен быть 32_FLOAT. Берите исходную картинку с HDRI Haven или sIBL Archive

2021-03-27 19:44 UTC, MikhailNakhatovich commented on graphics/ibl/ibl/Renderer.cpp
> +    D3D11_TEXTURE2D_DESC td = CD3D11_TEXTURE2D_DESC(DXGI_FORMAT_R8G8B8A8_UNORM, cubeSize, cubeSize, 6, 1, D3D11_BIND_SHADER_RESOURCE,
Картинку берём с HDRI Haven, только заранее конвертируем в PNG, чтобы был канал прозрачности.

2021-03-28 08:29 UTC, anthark commented on graphics/ibl/ibl/Renderer.cpp
> +    D3D11_TEXTURE2D_DESC td = CD3D11_TEXTURE2D_DESC(DXGI_FORMAT_R8G8B8A8_UNORM, cubeSize, cubeSize, 6, 1, D3D11_BIND_SHADER_RESOURCE,
А зачем? =0 А, это вы так решаете проблему с тем, что трехканальный формат может неправильно работать... 

Перевод в png создает проблему, которую  мы разбирали во второй лекции, про HDR. Яркость Солнца становится равной 1. Что неправильно, потому что тогда вам яркость всяких искусственных источников света придется делать 0.0001, например, и т.д. И тогда в локациях без солнца будет достаточно сложно что-то разобрать. Плюс относительная яркость каких-то мест в HDR картинке может отличаться больше чем в 255 раз и тогда при конвертации потеряются детали. 

Короче говоря, нужно все-таки исходную картинку держать в HDR формате. Конвертация в 4 канала легко делается при загрузке - нужно создать свой буфер под картинку такого же размера, но с четырьмя каналами, и в него переложить пиксели трехканальной, тогда будет то, что надо.

2021-03-28 08:30 UTC, anthark requested changes
Написал длинный коммент, мимо ревью, но его легко найти, я думаю =)

2021-03-28 13:50 UTC, anthark approved these changes
Хорошо, засчитано. 

Единственный момент, который имеет смысл переделать: вы добавили умножение environment текстуры на 7, чтобы она не была такая темная, если я правильно понял. Но получается, что у вас так environment сам по себе и объекты, которые вы рендерите имеют несвязанные между собой настройки яркости, вместо одной общей. 

Лучше с той же целью добавить масштабирование экспозиции в TonemapFilmic: 
float e = Exposure() * exposureRatio;

Джон такое разрешает, судя по его же референсу здесь: 
http://filmicworlds.com/blog/filmic-tonemapping-operators/

2021-03-28 13:50 UTC, merged